//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1318
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mommosoft.Capi.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InfoStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InfoStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mommosoft.Capi.Properties.InfoStrings", typeof(InfoStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request accepted.
        /// </summary>
        internal static string INFO_0000 {
            get {
                return ResourceManager.GetString("INFO_0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NCPI not supported by current protocol, NCPI ignored.
        /// </summary>
        internal static string INFO_0001 {
            get {
                return ResourceManager.GetString("INFO_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flags not supported by current protocol, flags ignored.
        /// </summary>
        internal static string INFO_0002 {
            get {
                return ResourceManager.GetString("INFO_0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert already sent by another application.
        /// </summary>
        internal static string INFO_0003 {
            get {
                return ResourceManager.GetString("INFO_0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many applications.
        /// </summary>
        internal static string INFO_1001 {
            get {
                return ResourceManager.GetString("INFO_1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logical block size too small; must be at least 128 bytes.
        /// </summary>
        internal static string INFO_1002 {
            get {
                return ResourceManager.GetString("INFO_1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer exceeds 64 kbytes.
        /// </summary>
        internal static string INFO_1003 {
            get {
                return ResourceManager.GetString("INFO_1003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message buffer size too small, must be at least 1024 bytes.
        /// </summary>
        internal static string INFO_1004 {
            get {
                return ResourceManager.GetString("INFO_1004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. number of logical connections not supported.
        /// </summary>
        internal static string INFO_1005 {
            get {
                return ResourceManager.GetString("INFO_1005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved.
        /// </summary>
        internal static string INFO_1006 {
            get {
                return ResourceManager.GetString("INFO_1006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message could not be accepted because of an internal busy condition.
        /// </summary>
        internal static string INFO_1007 {
            get {
                return ResourceManager.GetString("INFO_1007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS resource error (e.g. no memory).
        /// </summary>
        internal static string INFO_1008 {
            get {
                return ResourceManager.GetString("INFO_1008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMMON-ISDN-API not installed.
        /// </summary>
        internal static string INFO_1009 {
            get {
                return ResourceManager.GetString("INFO_1009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller does not support external equipment.
        /// </summary>
        internal static string INFO_100A {
            get {
                return ResourceManager.GetString("INFO_100A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller does only support external equipment.
        /// </summary>
        internal static string INFO_100B {
            get {
                return ResourceManager.GetString("INFO_100B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal application number.
        /// </summary>
        internal static string INFO_1101 {
            get {
                return ResourceManager.GetString("INFO_1101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal command or subcommand, or message length less than 12 octets.
        /// </summary>
        internal static string INFO_1102 {
            get {
                return ResourceManager.GetString("INFO_1102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message could not be accepted because of a queue full condition. The error
        ///code does not imply that COMMON-ISDN-API cannot receive messages directed to
        ///another controller, PLCI or NCCI..
        /// </summary>
        internal static string INFO_1103 {
            get {
                return ResourceManager.GetString("INFO_1103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue is empty.
        /// </summary>
        internal static string INFO_1104 {
            get {
                return ResourceManager.GetString("INFO_1104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue overflow: a message was lost. This indicates a configuration error. The only
        ///recovery from this error is to do the CAPI_RELEASE operation..
        /// </summary>
        internal static string INFO_1105 {
            get {
                return ResourceManager.GetString("INFO_1105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown notification parameter.
        /// </summary>
        internal static string INFO_1106 {
            get {
                return ResourceManager.GetString("INFO_1106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message could not be accepted because of an internal busy condition.
        /// </summary>
        internal static string INFO_1107 {
            get {
                return ResourceManager.GetString("INFO_1107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS resource error (e.g. no memory).
        /// </summary>
        internal static string INFO_1108 {
            get {
                return ResourceManager.GetString("INFO_1108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMMON-ISDN-API not installed.
        /// </summary>
        internal static string INFO_1109 {
            get {
                return ResourceManager.GetString("INFO_1109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller does not support external equipment.
        /// </summary>
        internal static string INFO_110A {
            get {
                return ResourceManager.GetString("INFO_110A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller supports only external equipment.
        /// </summary>
        internal static string INFO_110B {
            get {
                return ResourceManager.GetString("INFO_110B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort D-channel, level 2.
        /// </summary>
        internal static string INFO_3306 {
            get {
                return ResourceManager.GetString("INFO_3306", resourceCulture);
            }
        }
    }
}
