//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1318
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mommosoft.Capi.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProtocolStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProtocolStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mommosoft.Capi.Properties.ProtocolStrings", typeof(ProtocolStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 64 kbit/s with HDLC framing, always set..
        /// </summary>
        internal static string B1_0001 {
            get {
                return ResourceManager.GetString("B1_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 64 kbit/s bit-transparent operation with byte framing
        ///from the network..
        /// </summary>
        internal static string B1_0002 {
            get {
                return ResourceManager.GetString("B1_0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V.110 asynchronous operation with start/stop byte
        ///framing..
        /// </summary>
        internal static string B1_0004 {
            get {
                return ResourceManager.GetString("B1_0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V.110 synchronous operation with HDLC framing..
        /// </summary>
        internal static string B1_0008 {
            get {
                return ResourceManager.GetString("B1_0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 64 kbit/s bit-transparent operation with byte framing
        ///from the network.
        /// </summary>
        internal static string B1_0010 {
            get {
                return ResourceManager.GetString("B1_0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 64 kbit/s inverted with HDLC framing..
        /// </summary>
        internal static string B1_0020 {
            get {
                return ResourceManager.GetString("B1_0020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol {0}, {1}..
        /// </summary>
        internal static string Format {
            get {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }
    }
}
